# ————— Build Stage —————
FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY angular.json tsconfig*.json ./
COPY src ./src

RUN npm run build  # builda usando config do angular.json

# ————— Production Stage —————
FROM nginx:stable-alpine AS prod

COPY --from=build /app/dist/frontend-paapo/browser /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]